cc_library(
    name = "commdef",
    srcs = [
        "comm_def.h"
    ],
    hdrs = [
        "comm_def.h"
    ],
    deps = [
    ],
    copts = [
        "-std=c++11",
    ],
    visibility = ["//visibility:public"],
)
