cc_library(
    name = "comm_def",
    srcs = [
        "comm_def.h",
        "controller_def.h",
    ],
    hdrs = [
        "comm_def.h",
        "controller_def.h",
    ],
    deps = [
    ],
    copts = [
        "-std=c++11",
    ],
    visibility = ["//visibility:public"],
)
