cc_library(
    name = "tlog",
    srcs = [
        "tlog.cpp",
        "tlog.h",
    ],
    deps = [
    ],
)

cc_binary(
    name = "tlog_test",
    srcs = [
        "tlog_test.cpp",
    ],
    deps = [
        "//Comm/TLog:tlog",
    ],
)

