cc_library(
    name = "ip_tools_lib",
    srcs = [
        "iptables_tool.cpp",
    ],
    hdrs = [
        "iptables_tool.h",
    ],
    deps = [
        "//comm/commdef:comm_def_lib",
        "//comm/tlog:tlog_lib",
    ],
    copts = [
        "-std=c++11",
    ],
    visibility = ["//visibility:public"],
)
